### ISSUE TITLE
dep or go modules?

### ISSUE THREAD

**Issue by jpatters** [teramoby/speedle-plus#12]
I see both Gopkg files and go mod files in the repo. 
Which one should I be using? 
Can the one not being used be removed?

**Comment by bill828** [comment]
go mod is recommended.

I remained Gopkg because I'm using  old Golang version on some environments. I'll remove Gopkg files as soon as I upgrade go version on those environments. It will be done in one month.

**Comment by bill828** [comment]
This issue is fixed by PR #13 . So close this issue.
