### ISSUE TITLE
spctl reports an error with default setting

### ISSUE THREAD

**Issue by caiwl** [teramoby/speedle-plus#16]
$GOPATH/bin/spctl create service mysvc
Fail to parse URL parse "0.0.0.0:6733": first path segment in URL cannot contain colon
parse "0.0.0.0:6733": first path segment in URL cannot contain colon

**Comment by bill828** [comment]
This is a new issue imported by PR #15 .
At `cmd/spctl/command/root.go:ln 33`, the default value for command line `pms-endpoint` is `flag.DefaultPolicyMgmtEndPoint`, however the value of this constant is `0.0.0.0:6733` which is the default value for `PMS`.
